### ISSUE TITLE
老哥的q绑社工库还在吗，求分享

### ISSUE THREAD

**Issue by zhao-tan** [AdminWhaleFall/leaning-python#1]

**Comment by AdminWhaleFall** [comment]
> 复制这段内容后打开百度网盘APP，操作更方便哦。链接： https://pan.baidu.com/s/1LlPMF9wQQzRNcNmTz0dqMA 提取码：8888
## 请勿用于非法用途 [手动狗头🐕]

**Comment by AdminWhaleFall** [comment]
这个`repository`好久没维护了，部分代码不知道能不能用了。自个测试吧。
没事的话请 closed the issue。

**Comment by zhao-tan** [comment]
谢谢老哥，不会乱用的
